// Writes src/build-info.ts so the deployed Worker can state which commit it was built
// from. This exists for one reason: post-deploy verification needs to prove the expected
// version is the one actually serving. Before this, verify-production.yml inferred that
// from a fixed sleep plus "does /api/metrics exist", which stopped discriminating the
// moment that route shipped in every build.
//
// The file is generated, never committed (see .gitignore), and is produced by `npm run
// check` — the same command Cloudflare Workers Builds runs before `wrangler deploy`.
//
// Two independent sources for the SHA, because each has a way of being absent:
//   1. WORKERS_CI_COMMIT_SHA / GITHUB_SHA — set by Workers Builds and Actions.
//   2. `git rev-parse HEAD` — works in any clone, including if those names ever change.
// If neither yields a real SHA the value is "unknown", which no verifier will match, so
// the failure surfaces as "expected version never appeared" rather than a false pass.

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SHA = /^[0-9a-f]{7,40}$/;

function fromEnv() {
  for (const name of ["WORKERS_CI_COMMIT_SHA", "GITHUB_SHA", "CF_PAGES_COMMIT_SHA"]) {
    const value = (process.env[name] ?? "").trim().toLowerCase();
    if (SHA.test(value)) return value;
  }
  return null;
}

function fromGit() {
  try {
    const value = execFileSync("git", ["rev-parse", "HEAD"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] })
      .trim()
      .toLowerCase();
    return SHA.test(value) ? value : null;
  } catch {
    return null; // no git in the build container, or not a repository
  }
}

// Interpolated into a source file, so it is validated against SHA above rather than
// trusted — an unchecked env var here would be a code-injection path into the Worker.
const commit = fromEnv() ?? fromGit() ?? "unknown";

const out = fileURLToPath(new URL("../src/build-info.ts", import.meta.url));
writeFileSync(
  out,
  `// GENERATED by scripts/build-info.mjs — do not edit, do not commit.\nexport const BUILD_COMMIT = ${JSON.stringify(commit)};\n`
);
console.log(`build-info: BUILD_COMMIT=${commit}`);
